# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Applications/CMake.app/Contents/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/blair/Desktop/Projects/SearchC++

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/blair/Desktop/Projects/SearchC++

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/Applications/CMake.app/Contents/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/blair/Desktop/Projects/SearchC++/CMakeFiles /Users/blair/Desktop/Projects/SearchC++//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/blair/Desktop/Projects/SearchC++/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named 8-PuzzleC++

# Build rule for target.
8-PuzzleC++: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 8-PuzzleC++
.PHONY : 8-PuzzleC++

# fast build rule for target.
8-PuzzleC++/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/8-PuzzleC++.dir/build.make CMakeFiles/8-PuzzleC++.dir/build
.PHONY : 8-PuzzleC++/fast

Puzzle.o: Puzzle.cpp.o
.PHONY : Puzzle.o

# target to build an object file
Puzzle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/8-PuzzleC++.dir/build.make CMakeFiles/8-PuzzleC++.dir/Puzzle.cpp.o
.PHONY : Puzzle.cpp.o

Puzzle.i: Puzzle.cpp.i
.PHONY : Puzzle.i

# target to preprocess a source file
Puzzle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/8-PuzzleC++.dir/build.make CMakeFiles/8-PuzzleC++.dir/Puzzle.cpp.i
.PHONY : Puzzle.cpp.i

Puzzle.s: Puzzle.cpp.s
.PHONY : Puzzle.s

# target to generate assembly for a file
Puzzle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/8-PuzzleC++.dir/build.make CMakeFiles/8-PuzzleC++.dir/Puzzle.cpp.s
.PHONY : Puzzle.cpp.s

Search.o: Search.cpp.o
.PHONY : Search.o

# target to build an object file
Search.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/8-PuzzleC++.dir/build.make CMakeFiles/8-PuzzleC++.dir/Search.cpp.o
.PHONY : Search.cpp.o

Search.i: Search.cpp.i
.PHONY : Search.i

# target to preprocess a source file
Search.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/8-PuzzleC++.dir/build.make CMakeFiles/8-PuzzleC++.dir/Search.cpp.i
.PHONY : Search.cpp.i

Search.s: Search.cpp.s
.PHONY : Search.s

# target to generate assembly for a file
Search.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/8-PuzzleC++.dir/build.make CMakeFiles/8-PuzzleC++.dir/Search.cpp.s
.PHONY : Search.cpp.s

aStarNode.o: aStarNode.cpp.o
.PHONY : aStarNode.o

# target to build an object file
aStarNode.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/8-PuzzleC++.dir/build.make CMakeFiles/8-PuzzleC++.dir/aStarNode.cpp.o
.PHONY : aStarNode.cpp.o

aStarNode.i: aStarNode.cpp.i
.PHONY : aStarNode.i

# target to preprocess a source file
aStarNode.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/8-PuzzleC++.dir/build.make CMakeFiles/8-PuzzleC++.dir/aStarNode.cpp.i
.PHONY : aStarNode.cpp.i

aStarNode.s: aStarNode.cpp.s
.PHONY : aStarNode.s

# target to generate assembly for a file
aStarNode.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/8-PuzzleC++.dir/build.make CMakeFiles/8-PuzzleC++.dir/aStarNode.cpp.s
.PHONY : aStarNode.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/8-PuzzleC++.dir/build.make CMakeFiles/8-PuzzleC++.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/8-PuzzleC++.dir/build.make CMakeFiles/8-PuzzleC++.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/8-PuzzleC++.dir/build.make CMakeFiles/8-PuzzleC++.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... 8-PuzzleC++"
	@echo "... Puzzle.o"
	@echo "... Puzzle.i"
	@echo "... Puzzle.s"
	@echo "... Search.o"
	@echo "... Search.i"
	@echo "... Search.s"
	@echo "... aStarNode.o"
	@echo "... aStarNode.i"
	@echo "... aStarNode.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

